[package]
name = "isaacsim-mcp-server"
version = "0.6.0"
title = "Isaac Sim MCP Server"
description = "MCP server extension for Isaac Sim to enable communication with Claude and other AI assistants"
category = "Robotics"
keywords = ["mcp", "server", "socket", "simulation", "robotics"]

[dependencies]
"isaacsim.storage.native" = {}
"isaacsim.core.simulation_manager" = {}
"isaacsim.core.experimental.utils" = {}
"isaacsim.core.experimental.prims" = {}
"isaacsim.core.experimental.objects" = {}
"isaacsim.sensors.experimental.rtx" = {}
"isaacsim.asset.importer.urdf" = {}
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}



# Main python module this extension provides, it will be publicly available as "import isaac_sim_mcp_extension".
[[python.module]]
name = "isaac_sim_mcp_extension"



[python.pipapi]


[settings]
server.socket = 8766
server.host = "localhost"
